# 初始数据
user:
  lastName: Vic
  age: 20
  boss: false
  birth: 2019/07/01
  maps: {qq: 666, iphone: 888}
  lists:
    - Tom
    - Ccg
  dog:
    name: 小狗
    age: 8

address: 北京

#日志
logging:
  file:
    max-size: 10MB
  path: logs


debug: false
